services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alp-navigator
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production

networks:
  default:
    name: alp-navigator-net
